version: '3'
services: 
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - "8080:80"
        links:
            - app
    
    app:
        build: ./app
        tty: true
        volumes:
            - ./app/src/:/go/app/src
        links:
            - db

    db:
        build: ./db
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: PASSWORD
            MYSQL_USER: mysql
            MYSQL_PASSWORD: password
