version: '3'
services: 
    nginx:
        image: nginx
        ports: 
            - "8080:80"
    
    app:
        build: ./app
        tty: true
        volumes:
            - ./app:/go/app

    db:
        build: ./db
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: PASSWORD
            MYSQL_USER: mysql
            MYSQL_PASSWORD: password
